controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

all:
  path: /api
  controller: App\Controller\ApiController::fetchAll