controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
getAll:
  path: /nvd-api
  controller: App\Controller\ExternalApiController::getAll
  methods: ["GET"]

getById:
  path: /nvd-api/{id}
  controller: App\Controller\ExternalApiController::getById
  methods: ["GET"]

api_post_usuarios:
  path: /api/usuarios/
  controller: App\Controller\UserController::postCybedUser
  methods: ["POST"]
