controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

getAll:
  path: /api
  controller: App\Controller\ApiController::getAll
  methods: ["GET"]

getById:
  path: /api/{id}
  controller: App\Controller\ApiController::getById
  methods: ["GET"]
