controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_post_usuarios:
  path: /api/usuarios/
  controller: App\Controller\ApiController::postCybedUser
  methods: ["POST"]

api_post_login:
  path: /api/login/
  controller: App\Controller\ApiController::postCybedLogin
  methods: ["POST"]