controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

index:
  path: /
  controller: App\Controller\MainController::index

apiIndex:
  path: /api
  controller: App\Controller\MainController::apiIndex

# CVE 

nvd_get_cves:
  path: /nvd-api
  controller: App\Controller\ExternalApiController::getAll
  methods: GET

nvd_get_cve:
  path: /nvd-api/{id}
  controller: App\Controller\ExternalApiController::getById
  methods: GET

# USUARIOS

api_get_usuarios:
  path: /api/usuarios/
  controller: App\Controller\UserController::getAllCybedUsers
  methods: GET 

api_get_usuario:
  path: /api/usuarios/{id}
  controller: App\Controller\UserController::getCybedUser
  methods: GET 

api_post_usuario:
  path: /api/usuarios/
  controller: App\Controller\UserController::postCybedUser
  methods: POST

api_delete_usuario:
  path: /api/usuarios/{id}
  controller: App\Controller\UserController::deleteCybedUser
  methods: DELETE

api_put_usuario:
  path: /api/usuarios/{id}
  controller: App\Controller\UserController::putCybedUser
  methods: PUT

# ENTRADAS

api_get_entradas:
  path: /api/entradas/
  controller: App\Controller\EntryController::getAllEntries
  methods: GET

api_get_entrada:
  path: /api/entradas/{id}
  controller: App\Controller\EntryController::getEntry
  methods: GET

api_post_entrada:
  path: /api/entradas/
  controller: App\Controller\EntryController::postEntry
  methods: POST

api_put_entrada:
  path: /api/entradas/{id}
  controller: App\Controller\EntryController::putEntry
  methods: PUT

api_delete_entrada:
  path: /api/entradas/{id}
  controller: App\Controller\EntryController::deleteEntry
  methods: DELETE

# MENSAJES

api_get_mensajes:
  path: /api/mensajes/
  controller: App\Controller\MessageController::getAllMessages
  methods: GET

api_get_mensaje:
  path: /api/mensajes/{id}
  controller: App\Controller\MessageController::getMessage
  methods: GET

api_post_mensaje:
  path: /api/mensajes/
  controller: App\Controller\MessageController::postMessage
  methods: POST

api_put_mensaje:
  path: /api/mensajes/{id}
  controller: App\Controller\MessageController::putMessage
  methods: PUT

api_delete_mensaje:
  path: /api/mensajes/{id}
  controller: App\Controller\MessageController::deleteMessage
  methods: DELETE