controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

nvd_get_cves:
  path: /nvd-api
  controller: App\Controller\ExternalApiController::getAll
  methods: GET

nvd_get_cve:
  path: /nvd-api/{id}
  controller: App\Controller\ExternalApiController::getById
  methods: GET

api_get_usuarios:
  path: /api/usuarios/
  controller: App\Controller\UserController::getAllCybedUsers
  methods: GET 

api_get_usuario:
  path: /api/usuarios/{usuario}
  controller: App\Controller\UserController::getCybedUser
  methods: GET 

api_post_usuarios:
  path: /api/usuarios/
  controller: App\Controller\UserController::postCybedUser
  methods: POST

api_post_login_usuarios:
  path: /api/login/usuarios/
  controller: App\Controller\UserController::postLoginCybedUser
  methods: POST

api_get_entradas:
  path: /api/entradas/
  controller: App\Controller\EntryController::getAllEntries
  methods: GET
