controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_post_usuarios:
  path: /api/usuarios/
  controller: App\Controller\UserController::postCybedUser
  methods: ["POST"]

