controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

index:
  path: /
  controller: App\Controller\MainController::index

# CVE 

nvd_get_cves:
  path: /nvd-api
  controller: App\Controller\ExternalApiController::getAll
  methods: GET

nvd_get_cve:
  path: /nvd-api/{id}
  controller: App\Controller\ExternalApiController::getById
  methods: GET

# USUARIOS

api_get_usuarios:
  path: /api/usuarios/
  controller: App\Controller\UserController::getAllCybedUsers
  methods: GET 

api_get_usuario:
  path: /api/usuarios/{usuario}
  controller: App\Controller\UserController::getCybedUser
  methods: GET 

api_post_usuario:
  path: /api/usuarios/
  controller: App\Controller\UserController::postCybedUser
  methods: POST

api_delete_usuario:
  path: /api/usuarios/{usuario}
  controller: App\Controller\UserController::deleteCybedUser
  methods: DELETE

api_put_usuario:
  path: /api/usuarios/{usuario}
  controller: App\Controller\UserController::putCybedUser
  methods: PUT

# api_post_login_usuarios:
#   path: /api/login/usuarios/
#   controller: App\Controller\UserController::postLoginCybedUser
#   methods: POST

# ENTRADAS

api_get_entradas:
  path: /api/entradas/
  controller: App\Controller\EntryController::getAllEntries
  methods: GET


api_post_entrada:
  path: /api/crear/entrada/
  controller: App\Controller\EntryController::postEntry
  methods: POST
